extensions_folders = {
#NoName
    'NoName' : "/Documents/Other/Uncategorized",
#Audio
    '.aif' : "/Music/Media/Audio",
    '.cda' : "/Music/Media/Audio",
    '.mid' : "/Music/Media/Audio",
    '.midi' : "/Music/Media/Audio",
    '.mp3' : "/Music/Media/Audio",
    '.mpa' : "/Music/Media/Audio",
    '.ogg' : "/Music/Media/Audio",
    '.wav' : "/Music/Media/Audio",
    '.wma' : "/Music/Media/Audio",
    '.wpl' : "/Music/Media/Audio",
    '.m3u' : "/Music/Media/Audio",
#Text
    '.txt' : "/Documents/Text/TextFiles",
    '.doc' : "/Documents/Text/Microsoft/Word",
    '.docx' : "/Documents/Text/Microsoft/Word",
    '.odt ' : "/Documents/Text/TextFiles",
    '.pdf': "/Documents/Text/PDF",
    '.rtf': "/Documents/Text/TextFiles",
    '.tex': "/Documents/Text/TextFiles",
    '.wks ': "/Documents/Text/TextFiles",
    '.wps': "/Documents/Text/TextFiles",
    '.wpd': "/Documents/Text/TextFiles",
#Video
    '.3g2': "/Video",
    '.3gp': "/Video",
    '.avi': "/Video",
    '.flv': "/Video",
    '.h264': "/Video",
    '.m4v': "/Video",
    '.mkv': "/Video",
    '.mov': "/Video",
    '.mp4': "/Video",
    '.mpg': "/Video",
    '.mpeg': "/Video",
    '.rm': "/Video",
    '.swf': "/Video",
    '.vob': "/Video",
    '.wmv': "/Video",
#Images
    '.ai': "/Pictures",
    '.bmp': "/Pictures",
    '.gif': "/Pictures",
    '.ico': "/Pictures",
    '.jpg': "/Pictures",
    '.jpeg': "/Pictures",
    '.png': "/Pictures",
    '.ps': "/Pictures",
    '.psd': "/Pictures",
    '.svg': "/Pictures",
    '.tif': "/Pictures",
    '.tiff': "/Pictures",
    '.CR2': "/Pictures",
#Internet
    '.asp': "/Documents/Other/Internet",
    '.aspx': "/Documents/Other/Internet",
    '.cer': "/Documents/Other/Internet",
    '.cfm': "/Documents/Other/Internet",
    '.cgi': "/Documents/Other/Internet",
    '.pl': "/Documents/Other/Internet",
    '.css': "/Documents/Other/Internet",
    '.htm': "/Documents/Other/Internet",
    '.js': "/Documents/Other/Internet",
    '.jsp': "/Documents/Other/Internet",
    '.part': "/Documents/Other/Internet",
    '.php': "/Documents/Other/Internet",
    '.rss': "/Documents/Other/Internet",
    '.xhtml': "/Documents/Other/Internet",
#Compressed
    '.7z': "/Documents/Other/Compressed",
    '.arj': "/Documents/Other/Compressed",
    '.deb': "/Documents/Other/Compressed",
    '.pkg': "/Documents/Other/Compressed",
    '.rar': "/Documents/Other/Compressed",
    '.rpm': "/Documents/Other/Compressed",
    '.tar.gz': "/Documents/Other/Compressed",
    '.z': "/Documents/Other/Compressed",
    '.zip': "/Documents/Other/Compressed",
#Disc
    '.bin': "/Documents/Other/Disc",
    '.dmg': "/Documents/Other/Disc",
    '.iso': "/Documents/Other/Disc",
    '.toast': "/Documents/Other/Disc",
    '.vcd': "/Documents/Other/Disc",
#Data
    '.csv': "/Documents/Programming/Database",
    '.dat': "/Documents/Programming/Database",
    '.db': "/Documents/Programming/Database",
    '.dbf': "/Documents/Programming/Database",
    '.log': "/Documents/Programming/Database",
    '.mdb': "/Documents/Programming/Database",
    '.sav': "/Documents/Programming/Database",
    '.sql': "/Documents/Programming/Database",
    '.tar': "/Documents/Programming/Database",
    '.xml': "/Documents/Programming/Database",
    '.json': "/Documents/Programming/Database",
#Executables
    '.apk': "/Documents/Other/Executables",
    '.bat': "/Documents/Other/Executables",
    '.com': "/Documents/Other/Executables",
    '.exe': "/Documents/Other/Executables",
    '.gadget': "/Documents/Other/Executables",
    '.jar': "/Documents/Other/Executables",
    '.wsf': "/Documents/Other/Executables",
#Fonts
    '.fnt': "/Documents/Other/Fonts",
    '.fon': "/Documents/Other/Fonts",
    '.otf': "/Documents/Other/Fonts",
    '.ttf': "/Documents/Other/Fonts",
#Presentations
    '.key': "/Documents/Text/Presentations",
    '.odp': "/Documents/Text/Presentations",
    '.pps': "/Documents/Text/Presentations",
    '.ppt': "/Documents/Text/Presentations",
    '.pptx': "/Documents/Text/Presentations",
#Programming
    '.c': "/Documents/Programming/C&C++",
    '.class': "/Documents/Programming/Java",
    '.dart': "/Documents/Programming/Dart",
    '.py': "/Documents/Programming/Python",
    '.sh': "/Documents/Programming/Shell",
    '.swift': "/Documents/Programming/Swift",
    '.html': "/Documents/Programming/html",
    '.h': "/Documents/Programming/html",
#Spreadsheets
    '.ods' : "/Documents/Text/Microsoft/Excel",
    '.xlr' : "/Documents/Text/Microsoft/Excel",
    '.xls' : "/Documents/Text/Microsoft/Excel",
    '.xlsx' : "/Documents/Text/Microsoft/Excel",
#System
    '.bak' : "/Documents/Text/Other/System",
    '.cab' : "/Documents/Text/Other/System",
    '.cfg' : "/Documents/Text/Other/System",
    '.cpl' : "/Documents/Text/Other/System",
    '.cur' : "//Documents/Text/Other/System",
    '.dll' : "/Documents/Text/Other/System",
    '.dmp' : "/Documents/Text/Other/System",
    '.drv' : "/Documents/Text/Other/System",
    '.icns' : "/Documents/Text/Other/System",
    '.ico' : "/Documents/Text/Other/System",
    '.ini' : "/Documents/Text/Other/System",
    '.lnk' : "/Documents/Text/Other/System",
    '.msi' : "/Documents/Text/Other/System",
    '.sys' : "/Documents/Text/Other/System",
    '.tmp' : "/Documents/Text/Other/System",
}